### ISSUE TITLE
Launch tokens from previous SDK don't seem to be compatible with the new one

### ISSUE THREAD

**Issue by mikehearn** [01org/linux-sgx#14]
I saw that the 1.6 release has now been dropped ... I realise it's a bit early and there are no release notes yet, etc, but I figured I'd report an issue I hit immediately: the sample apps stopped working.

It took a lot of messing around and I'm not entirely sure how I fixed it, but as far as I can tell I did the following:

* Uninstalled the prior PSW and SDK completely (means ensuring aesmd is stopped)
* Re-downloaded the prebuilt binary files
* did a `make clean` and `make DEBUG=1`
* Reinstalled the PSW and SDK, this time the SDK went to a local directory
* Deleted ~/launch.token 

I hadn't realised that the last step might be necessary and was puzzled for an hour or so as to why the sample apps had stopped working with a generic error that told me nothing. You should probably consider *NOT* caching launch tokens in the sample apps, or at the very least, caching them to the local directory and erasing them on "make clean" because it is not at all obvious that this file is being created and reused unless you read the code.

**Comment by zhaohuidu** [comment]
After the code update, the launch token is changed. But the launch token is likely to be changed if the enclave is recompiled since enclave measure (MRENCLAVE) will change.
When urts finds that the old launch token doesn't work, it will try to query a new one from AESM.

So the problem should not come from the launch token.

Would you please help to provide more information such as how do you build the Sample Code? 
Is the SDK updated before you building the Sample Code?

Usually, if both PSW and SDK is reinstalled, the problem should be solved.

**Comment by mikehearn** [comment]
For me it took much more than just reinstalling the PSW and SDK. Perhaps there was a mismatch somewhere between whether debug mode was enabled or not at build time.

If there are no theories as to what can cause such upgrade issues, then let's close this.
