### ISSUE TITLE
aesmd - EINIT returns 2 on startup

### ISSUE THREAD

**Issue by donporter** [01org/linux-sgx#44]
I am on Ubuntu 16.04, using the latest master for linux-sgx and linux-sgx-driver.  When I start aesmd, I get this message in dmesg:

[448620.384306] isgx: [8831:0x00007fd8aeb00000] EINIT returned 2

I assume this is not good.  Any advice?

Thanks!

**Comment by ENOTTY** [comment]
According to the [Programming Reference](https://software.intel.com/sites/default/files/managed/48/88/329298-002.pdf), return code of 2 is Invalid Attribute. This could happen if your PSW is out of date.

**Comment by donporter** [comment]
As far as I can tell, I am using the latest PSW built from master.  I uninstalled, pulled the latest master, and did a clean rebuild/reinstall and the issue still happens.

Is it possible the prebuilts are behind master?

**Comment by zhaohuidu** [comment]
The interface between Linux-sgx and Linux-sgx-driver has been updated after 1.6 tag.
If you have updated one of them from 1.6 tag to latest code, you should update the other one too.
It is likely that unmatched version used

**Comment by sean-jc** [comment]
@donporter - If AESMD starts correctly, i.e. you can obtain launch tokens for you enclaves, then the "EINIT returned 2" message is benign.  The AESM first tries to load the Launch Enclave using a non-production signature/key, and then retries using a production signature/key if EINIT fails due to an invalid attribute, i.e. incorrect LE pubkey hash.  The driver logs the EINIT failure as it is unaware that failure is expected (on some platforms).

This issue can be closed unless there is an actual failure, the message itself is a "feature".
